### ISSUE TITLE
Task 1-UX Task

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#1]
# Task 1- UX Task

**OPEN TO ALL.**
NO need to claim this issue.
NO submission will be accepted after **16th December, 11:59 PM**.

Your **First Task** is based on a basic understanding of User Experience and User flow. This is a **20 points** task.

TechTerra as the name suggests is a platform designed for the IIITA community, offering a dynamic space for students, faculty, alumni and recruiters alike. At TechTerra, students have the opportunity to showcase their **skills, projects, and achievements, creating a comprehensive portfolio** that resonates with potential employers and collaborators. Through detailed student profiles, alumni and recruiters can easily connect with individuals whose skills align with their organizational needs, fostering a bridge between academia and industry. Going beyond traditional academic boundaries, TechTerra hosts innovation **challenges and hackathons** organized by IIITA, providing students with opportunities to apply their skills in real-world scenarios. These events also serve as a platform for companies to discover emerging talent and groundbreaking solutions.

😊**If you guys can think of more related features for the website you are free to add them in your Userflow**

> 💡The task needs to be done on **FigJam**. FigJam is free to use and doesn't need to download. It is very easy to learn and hardly takes 15 minutes to learn. If you are unclear on how to use it, check the tutorial here: https://www.youtube.com/watch?v=RVNuArHH5WM
> 

## Procedure:

1. Think about how the flow of the website will be for an average user who has just clicked on the website’s link and is opening it for the first time. The user is assumed to be unclear about the functionalities of the website.
2. You have to decide how the user will move through the website, what steps will he need to take, and in which order, for eg. the user first might need to sign up to the website, might want to search for the current hackathons, maybe wants to add a project in his profile, etc.
3. Essentially, you have to design a ‘single flow’ for a user who wants to make a comprehensive portfolio for himself or have to participate in any current happenings in the college etc.
4. Finally, create your ideal user flow in a FigJam file and provide its link (in a .txt file). Submit your txt files in the UX TASK folder only.

</br>

If you are unclear about user flow diagrams check this short video here: https://www.youtube.com/watch?v=cvYhuowazh0

</br>

> PRO-TIP: The secret to creating a powerful user flow is to first research and gain an understanding of how a given problem statement is addressed. As a result, the first and most important thing you must do before beginning to build your user flow is to search other websites that deal with a similar problem statement of buying and selling goods. And take note of the key features they use (basically their user flow).
> 

</br>

## **MDC (Minimum Design Criteria):**

The user flow can be very simple, but it must at least fulfill the basic functionality of the website, which is that users should be able to buy and sell items. The flow should start with the user entering the site for the first time and continue until his job is done.

> PRO-TIP: Try to make an elaborate user-flow…that makes your task of building the further website way too easy. meticulously decide upon each feature you add.
> 

For any doubts related to the task or the submission process, you can always ping us on discord. Use the tag @TechTerra to notify the mentors. We will be happy to help.

**Comment by Reene-Simon** [comment]
@D-Hacker26 there is a typo in the issue description. Instead of December it's given October. Do make the relevant changes.
