### ISSUE TITLE
Short Task- Gradient effect 

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#144]
**OPEN TO ALL** !

**No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 18st December 10 P.M.**

This is an extension of the  **pen tool task given- you have to exactly copy the gradient effect shown in the figure !!**

💡This Task can be done only after you have completed the Pen Tool Task..

⭐In this task, you are supposed to copy the given vector in Illustrator or Figma using the pen tool and *exactly copy the gradient effect shown* and submit the **Illustrator file (.ai file) or a text file with a Figma link.**

Make sure that you use the color dropper tool to get the perfect shade of the color

> 💡 This task can be done in Adobe Illustrator or Figma.
> 

## **Submission Guideline:**

- Submit the illustrator file in the "Task-2" Folder only.
- submit the link of the figma file/ illustrator file in a .txt file only.

> This task is for 🏆1**5 points.**
> 

## **MDC (Minimum Design Criteria):**

💡**In this task you can only submit one PR once submitted you wont get chance to edit.** The vector which you are going to copy should look like the vector given.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

![photo](https://github.com/opencodeiiita/TechTerra/assets/128993800/0d73561f-df09-4c53-9760-3ade42e3f656)

**Comment by QuantTitan** [comment]
c
