### ISSUE TITLE
Short Task 2

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#17]
**OPEN TO ALL No need to claim this issue NO SUBMISSION WILL BE ACCEPTED AFTER 15th December 10 PM**

While you are working on the best user flow for the TechTerra website, here is another short task to test your thinking 🤔 as User Experience Designer!.

It is a very basic Task! 😊😊 You just need to  write 3 UI/UX Laws with explanation that you feel are important on a google doc.
- Provide the link of google docs in a .txt file. Make sure that the link is accessible (and not private).
- Submit your txt files in the 'Short Task 2' folder only.

Happy UXing contributors!

**Comment by Anshkaran7** [comment]
Short Task Completed #53
