### ISSUE TITLE
Hero Section Design

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#205]
**OPEN TO ALL.**

NO need to claim this issue.

NO submission will be accepted after **23rd December, 11:59 PM**.

Your next **Task** is to design the **Hero Section** of the Website TechTerra. This is a 🌟**20 points** task.

TechTerra as the name suggests is a platform designed for the IIITA community, offering a dynamic space for students, faculty, alumni and recruiters alike. At TechTerra, students have the opportunity to showcase their **skills, projects, and achievements, creating a comprehensive portfolio** that resonates with potential employers and collaborators. Through detailed student profiles, alumni and recruiters can easily connect with individuals whose skills align with their organizational needs, fostering a bridge between academia and industry. Going beyond traditional academic boundaries, TechTerra hosts innovation **challenges and hackathons** organized by IIITA, providing students with opportunities to apply their skills in real-world scenarios. These events also serve as a platform for companies to discover emerging talent and groundbreaking solutions.

The task needs to be done on **Figma**. Figma is free to use and doesn't need to download. It is very easy to learn and hardly takes 20 minutes to learn. If you are unclear on how to use it, check the tutorial here: https://www.youtube.com/watch?v=jk1T0CdLxwU&t=784s

For those who don’t know what hero section of a website is and how should a hero section look like, Pls refer to this video, it will surely give you a brief about it:

**link 1:** https://www.youtube.com/watch?v=KUgGLJxxghY

**link 2:** https://www.youtube.com/watch?v=LJbkLdtEW00&t=252s

## **Procedure:**

1. Your task is to decide on the Hero Section of the website. It is essentially nothing but the landing page of a website. Whenever a user (maybe visited for the first time, maybe keeps on visiting), clicks on the link of the website the first screen that appears is the Home Page.
2. You have to design the Hero Section of the home page.
3. Remember, the user has not yet signed in or might not have registered this is just the screen that comes up once the user clicks on the link of the website!
4. Keep in mind the key functionality of the website as the key functionalities must be fulfilled by the Hero Section itself the user should not feel the need to scroll down for major actions.
5. Finally, create your ideal Home page on a Figma file and provide its link (in a .txt file). Submit your txt files in the **Hero Section Design** folder only.

> ✨PRO-TIP: Designing any piece of UI requires the following basic steps: firstly research similar websites’ hero sections (note down the key elements the placement and the arrangement) and get familiar with hero sections, secondly the wire-frame (deciding where to place which element and what all has to be placed on the page) of the home page must be done, thirdly the visual design must be given (deciding the color scheme, the font styles, weight and size, the graphics on the page) and implementing the visual design, and finally some basic touch-ups!!
> 

## **MDC (Minimum Design Criteria):**

The home page of the website should look like a home page. It must have the logo(which you can select from the net for the time being), the call to action buttons, etc. Make the Hero Section as appealing as possible coz that's when users would want to continue on the website further.

> ✨PRO-TIP: You must search Figma Mirror on google and then select our frame on Figma and you would be able to see how your website would look on the screen. Take references of sizes and spacing from there. Make sure you maintain consistency in your design.
> 

> ✨PRO-TIP: Refer to the above 2 links on hero sections! They will give you a hell lot of ideas about Hero Sections and their designs.
> 

For any doubts related to the task or the submission process, you can always ping us on discord. We will be happy to help!!

**Comment by kushal7201** [comment]
Claim

**Comment by D-Hacker26** [comment]
> Claim

this issue is open for all
