### ISSUE TITLE
Login/Signup Design

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#240]
**OPEN TO ALL.**

NO need to claim this issue.

NO submission will be accepted after **26th December, 11:59 PM**.

Your next **Task** is to design the Login/Signup page of the Website TechTerra. This is a 🌟**20 points** task.

TechTerra as the name suggests is a platform designed for the IIITA community, offering a dynamic space for students, faculty, alumni and recruiters alike. At TechTerra, students have the opportunity to showcase their **skills, projects, and achievements, creating a comprehensive portfolio** that resonates with potential employers and collaborators. Through detailed student profiles, alumni and recruiters can easily connect with individuals whose skills align with their organizational needs, fostering a bridge between academia and industry. Going beyond traditional academic boundaries, TechTerra hosts innovation **challenges and hackathons** organized by IIITA, providing students with opportunities to apply their skills in real-world scenarios. These events also serve as a platform for companies to discover emerging talent and groundbreaking solutions.

The task needs to be done on **Figma**. Figma is free to use and doesn't need to download. It is very easy to learn and hardly takes 20 minutes to learn. If you are unclear on how to use it, check the tutorial here: https://www.youtube.com/watch?v=jk1T0CdLxwU&t=784s

## **Procedure:**

1. Your task is to decide on the Login/Signup page of the website.
2. Keep in mind the key functionality of the website as the key functionalities must be fulfilled by the Hero Section itself the user should not feel the need to scroll down for major actions.
3. Finally, create your ideal Login/Signup page on a Figma file and provide its link (in a .txt file). Submit your txt files in the **Login/Signup Design** folder only.

> ✨PRO-TIP: Designing any piece of UI requires the following basic steps: firstly research similar websites  (note down the key elements the placement and the arrangement) and get familiar with it, secondly the wire-frame (deciding where to place which element and what all has to be placed on the page) of the page must be done, thirdly the visual design must be given (deciding the color scheme, the font styles, weight and size, the graphics on the page) and implementing the visual design, and finally some basic touch-ups!!
> 

## **MDC (Minimum Design Criteria):**

The  page of the website should look like a Login/Signup page. The page should feature a clean and simple design, with prominent call-to-action buttons that use contrasting colors to draw attention. User-friendly forms, with clear labels and logical grouping of information, contribute to a seamless experience. Password strength indicators and robust error handling mechanisms enhance security and usability .

> ✨PRO-TIP: You must search Figma Mirror on google and then select our frame on Figma and you would be able to see how your website would look on the screen. Take references of sizes and spacing from there. Make sure you maintain consistency in your design.
> 

For any doubts related to the task or the submission process, you can always ping us on discord. We will be happy to help!!

**Comment by Rohit-110** [comment]
Claim
