### ISSUE TITLE
Footer Design

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#264]
**OPEN TO ALL.**

NO need to claim this issue.

NO submission will be accepted after **29th December, 11:59 PM**.

Your next **Task** is to design the Footer Section of the Website TechTerra. This is a 🌟**15** **points** task.

TechTerra🧑‍💻 as the name suggests is a platform designed for the IIITA community, offering a dynamic space for students, faculty, alumni and recruiters alike. At TechTerra, students have the opportunity to showcase their **skills, projects, and achievements, creating a comprehensive portfolio** that resonates with potential employers and collaborators. Through detailed student profiles, alumni and recruiters can easily connect with individuals whose skills align with their organizational needs, fostering a bridge between academia and industry. Going beyond traditional academic boundaries, TechTerra hosts innovation **challenges and hackathons** organized by IIITA, providing students with opportunities to apply their skills in real-world scenarios. These events also serve as a platform for companies to discover emerging talent and groundbreaking solutions

💡The task needs to be done on **Figma**. Figma is free to use and doesn't need to download. It is very easy to learn and hardly takes 20 minutes to learn. If you are unclear on how to use it, check the tutorial here: https://www.youtube.com/watch?v=jk1T0CdLxwU&t=784s

## Procedure:

1. Your task is to decide on the Footer Section of the website. It is essentially nothing but the landing page of a website. Whenever a user reaches the end of the home page or any page for that matter he/she ends up seeing the footer of the website.
2. You have to design the Footer of the website.
3. Remember that this is the section that lets the user know about the organization of TechTerra, copywriting of the website, social media handles of the organization, etc.
4. Finally, create your ideal footer section on a Figma file and provide its link (in a .txt file). Submit your txt files in the **Footer Design** folder only.

> ✨PRO-TIP: Designing any piece of UI requires the following basic steps: firstly research similar websites’ footer sections (note down the key elements the placement and the arrangement) and get familiar with footer sections, secondly the wire-frame (deciding where to place which element and what all has to be placed on the page) of the home page must be done, thirdly the visual design must be given (deciding the color scheme, the font styles, weight and size, the graphics on the page) and implementing the visual design, and finally some basic touch-ups!!
> 

## **MDC (Minimum Design Criteria):**

The Footer Section of the website should look like a footer section. It must have the logo(which you have already made), the organization of the website, the copywriting, the social media handles, etc. Remember that the **same theme** is followed in making the footer the theme used on the home page. Make sure the footer looks good and just as the footers look on general websites. Try to keep the options on the footer quite minimal. Only good designs will be merged.

> ✨PRO-TIP: You must search Figma Mirror on google and then select our frame on Figma and you would be able to see how your website would look on the screen. Take references of sizes and spacing from there. Make sure you maintain consistency in your design.
> 

For any doubts related to the task or the submission process, you can always ping us on discord. We will be happy to help!!🚀🚀

**Comment by kushal7201** [comment]
Claim

**Comment by D-Hacker26** [comment]
@kushal7201 the issue is open for all...
