### ISSUE TITLE
Fun Task- Play the Game

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#265]
**OPEN TO ALL**

**No** need to claim this issue.

NO SUBMISSION WILL BE ACCEPTED AFTER **29th December 11:59 PM.**

For this task you just have to play the game named ‘Can’t Unsee’. The task is for **20 points**. This game will improve your understanding of UI/UX. Submit the screenshot in the **FUN Task** folder only ALSO **kindly attach the screenshot in the PR** **comment as well under the issue number!.**

Link to the game-https://cantunsee.space/

## For other players:

You have to play this game at least up to the medium level. At least complete the entire medium level and bag 4000 points minimum and then upload a screenshot of the same in the PR you make. If you have bagged less than 4000 points then play the game again and then submit the ss as PRs with less than 4000 points won't be merged.

**🌟Make sure you upload the screenshot of the whole screen (with your task bar, time, google account etc visible in the ss) !!**

**🌟If any type of plagiarism is found….50 points of that participant will be deducted from the leaderboard.**

**Comment by Lokendrakushwah12** [comment]
![Screenshot_20231227-174816.png](https://github.com/opencodeiiita/TechTerra/assets/118094744/a55c2fed-9b53-4791-acbd-87dfa30b0654)

**Comment by D-Hacker26** [comment]
@Lokendrakushwah12 make a PR and then add your ss

**Comment by Lokendrakushwah12** [comment]
Oh my bad let me do that

**Comment by Apoorv012** [comment]
When does the game end?

**Comment by D-Hacker26** [comment]
@Apoorv012 the game ends after the hard level....you have take a ss as soon as you complete 4000 points
