### ISSUE TITLE
Talking to Aliens👽

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#319]
**OPEN FOR ALL !**

 **No need to claim. No submission will be considered after 4th Jan 11.59pm.**

Imagine aliens👽 have landed on Earth and want to learn about the company - Amul . But since they don’t speak your language, it needs to be explained with five symbols (like icons) or vectors. Each participant makes or gathers five simple vectors to communicate with the aliens.

## Procedure:

1. Design 5 vectors (or use icons) that will help the alien understand about Amul.
2. Add the 5 vectors or icons on your figma file.
3. Place the figma link in a .txt folder and submit the file in ‘Talking to Aliens’ folder ONLY.

## **Minimum Design Criteria (MDC):**

No changes will be suggested. Only single submission is allowed that will either be accepted or rejected depending on the accuracy of replication. Final decision resides with the mentors, no claim can be made on their decision.

**Comment by Apoorv012** [comment]
Do we need to design the vectors, or use pre-made vectors?

**Comment by D-Hacker26** [comment]
@Apoorv012 as its a 5 points task only....you can use pre made vectors
