### ISSUE TITLE
Portfolio design

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#333]
**OPEN TO ALL.**

NO need to claim this issue.

NO submission will be accepted after **8th January, 11:59 PM**.

Your next **Task** is to design the **PORTFOLIO PAGE** of the Website TechTerra🧑‍💻. This is a 🌟**50** **points(MAX)** task. *Partial points well be awarded according to the work that you have done*.

This is a new page of the our website TechTerra and one of the 🚀**most important** pages. The portfolio page should contain all the necessary information about the user like the profile photo, bio, experience, skills, projects, hackathons, education, important links, contacts, prizes etc etc…you may imagine it like a mini linkedIn for info. You may even add a section where the person can add his resume pdf. 💡THINK ACCORDINGLY BEFORE IMPLEMENTING!!

💡The task needs to be done on **Figma**. Figma is free to use and doesn't need to download. It is very easy to learn and hardly takes 20 minutes to learn. If you are unclear on how to use it, check the tutorial here: https://www.youtube.com/watch?v=jk1T0CdLxwU&t=784s

## Procedure:

1. Your task is to design the Portfolio page for TechTerra.
2. Make sure that the theme/color scheme of the website that you have made and the color scheme are maintained.
3. Finally, create your ideal  section on a Figma file and provide its link (in a .txt file). Submit your txt files in the **Portfolio design** folder only.

> ✨PRO-TIP: Designing any piece of UI requires the following basic steps: firstly research similar websites’ offer/sale sections (note down the key elements the placement and the arrangement) and get familiar with those sections, secondly the wire-frame (deciding where to place which element and what all has to be placed on the page) of the home page must be done, thirdly the visual design must be given (deciding the color scheme, the font styles, weight and size, the graphics on the page) and implementing the visual design, and finally some basic touch-ups!!
> 

## **MDC (Minimum Design Criteria):**

Besides containing all the important info about the user the portfolio section should be a good piece of UI/UX design as well….you can take inspiration from various portfolio websites designs available on internet and then implement it in your own way…take sure the design is decent but attractive.

> ✨PRO-TIP: You must search Figma Mirror on google and then select our frame on Figma and you will be able to see how your website would look on the screen. Take references of sizes and spacing from there. Make sure you maintain consistency in your design.
> 

You can always ping us on discord for any doubts related to the task or the submission process. We will be happy to help!!

**Comment by kushal7201** [comment]
Claim

**Comment by D-Hacker26** [comment]
@kushal7201 issue is open for all
