### ISSUE TITLE
FINAL TASK🚀

### ISSUE THREAD

**Issue by D-Hacker26** [opencodeiiita/TechTerra#346]
This task is for **50 points**. The deadline is till **12th Jan 10:00 PM** 

You just have to Assemble the entire website, TechTerra.

The website TechTerra will consists of **5 pages**, so the nav bar will have ⭐5 sections- Home, Portfolio, Builder, Blogs, Hackathons.

1. **Page 1-Home page:** first place the nav bar with the logo you designed, then the hero section, below that place the login and signup page, then place the testimonials section and finally place the footer.
2. **Page 2-Portfolio:** first the nav bar then place the complete portfolio section and finally the footer.
3. **Page 3-Builders:** first place the nav bar + the leaderboard you designed + the  top projects section + finally the footer.
4. **Page 4-Blogs:** nav bar+ complete bog section + footer
5. **Page 5-Hackathons section:**  nav bar + open hackathons section + upcoming hackathons section + past hackathons section + finally the footer section.

💡If you haven't made any of the sections previously make it now for this task.

🌟You may make some changes in your previously submitted designs in order to make the final look of the website good and attractive.

Submit the properly assembled pages(5 in number) of TechTerra, create your ideal website design on a Figma file and provide its link (in a .txt file). Submit your txt files in the  **Final Task** folder only.

**Comment by sarthakvermaa** [comment]
CLAIM
